@startuml
'https://plantuml.com/class-diagram


interface IGameItem{
    game_id: string;
    verbose_name_rus: string;
    verbose_name_eng: string;
    verbose_name_ukr: string;
    verbose_name_pln: string;
    cost: decimal;
}

class Item extends IGameItem{
unique: boolean
}
class Weapon extends Item
class Ammo extends Item
class Addon extends Item
class Artifact extends Item
class Armor extends Item
class MonsterPart extends Item
class Another extends Item

class Character extends IGameItem{
    place: Location
    name: string
}

class Location{
name: string
}

class Quest{
    asker: Character
    target: QuestTarget
    payments: QuestPayment[]
    stage: int
    once: boolean

    getType() -> QuestType
}

enum QuestType{}

abstract  class QuestTarget{
    count: int
}

class ItemQuestTarget extends QuestTarget{
    item: Item
    count: int;
}

class WeaponQuestTarget extends ItemQuestTarget{
    state: ItemState
}

class ArtefactQuestTarget extends ItemQuestTarget{

}

class KillQuestTarget extends QuestTarget{
    stalker: Stalker
}

class DestroyBaseQuestTarget extends QuestTarget{
    base: StalkersBase;
}

class ProtectBaseQuestTarget extends QuestTarget{
    base: StalkersBase;
}

class QuestPayment{
    item: Item
    count: int
    quest: Quest
}

Quest::asker <-- Character
Quest::target <-- QuestTarget
Quest::payments <-- QuestPayment
Character::place <-- Location

abstract class ItemObtaining{
    item: Item
}

class CiclicQuestItemObtaining extends ItemObtaining{
    quest: Quest
    is_random(): boolean
}

class StoryQuestItemObtaining extends ItemObtaining{
    quest: StoryQuest
}

class TradeItemObtaining  extends ItemObtaining{
    trader: Character
    price: int
    count: int
    probability: Decimal
}

TradeItemObtaining::trader <-- Character

class StoryQuest{
    name: string
    asker: Character
}

ItemObtaining::item <-- Item
CiclicQuestItemObtaining::quest <-- Quest
StoryQuest::asker <-- Character

class FromNpcItemObtaining extends ItemObtaining{
    npc_groups: NpcGroup[]
    locations: Location[]
}

class TresuareItemObtaining extends ItemObtaining{
    npcLevel: NpcLevel
}


@enduml
