# Generated by Django 5.0.4 on 2024-05-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recept",
            name="anomaly_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="recept",
            unique_together={("anomaly_id", "cel_raw")},
        ),
    ]
