# Generated by Django 4.1.3 on 2022-12-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclicquest",
            name="condlist_str",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="cyclicquest",
            name="map_location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cyclicquest",
            name="one",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cyclicquest",
            name="reward_money",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cyclicquest",
            name="target_cond_str",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cyclicquest",
            name="target_count",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
