# Generated by Django 5.0.4 on 2024-05-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0002_alter_recept_anomaly_id_alter_recept_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="recept",
            unique_together={("anomaly_id", "condition_raw")},
        ),
    ]
