# Generated by Django 5.0.4 on 2024-05-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0003_alter_recept_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="spawnreward",
            name="custom_spawn_section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game_parser.customspawnitem",
                verbose_name="Кастомная секция спавна",
            ),
        ),
    ]
