# Generated by Django 4.1.3 on 2022-12-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0003_rename_one_cyclicquest_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclicquest',
            name='hide_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cyclicquest',
            name='reward_treasure',
            field=models.BooleanField(default=False),
        ),
    ]
