# Generated by Django 5.0.4 on 2024-05-13 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0004_spawnreward_custom_spawn_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameVertex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vertex_id", models.PositiveIntegerField(unique=True)),
                ("location_name", models.CharField(max_length=128)),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game_parser.location",
                    ),
                ),
            ],
        ),
    ]
