# Generated by Django 4.1.3 on 2022-12-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0004_cyclicquest_hide_reward_cyclicquest_reward_treasure"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclicquest",
            name="defend_target_str",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cyclicquest",
            name="reward_dialog_str",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="cyclicquest",
            name="reward_relation_str",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
