# Generated by Django 5.0.4 on 2024-05-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0005_gamevertex"),
    ]

    operations = [
        migrations.AddField(
            model_name="spawnreward",
            name="game_vertex_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game_parser.gamevertex",
                verbose_name="Узел графа игры. Нужен для связи с локацией",
            ),
        ),
    ]
