# Generated by Django 5.0.4 on 2024-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0006_spawnreward_game_vertex_obj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamevertex",
            name="location_name",
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="edges_raw",
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="game_point_x",
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="game_point_y",
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="game_point_z",
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="level_id_raw",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="level_point_x",
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="level_point_y",
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="level_point_z",
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="level_points_raw",
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="level_vertex_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="gamevertex",
            name="vertex_type_raw",
            field=models.CharField(max_length=512),
        ),
    ]
