# Generated by Django 5.0.4 on 2024-05-18 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "game_parser",
            "0007_remove_gamevertex_location_name_gamevertex_edges_raw_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamevertex",
            options={"verbose_name": "Узел графа игры"},
        ),
        migrations.AlterField(
            model_name="gamevertex",
            name="level_vertex_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="spawnreward",
            name="custom_spawn_section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spawn_rewards",
                to="game_parser.customspawnitem",
                verbose_name="Кастомная секция спавна",
            ),
        ),
        migrations.AlterField(
            model_name="spawnreward",
            name="game_vertex_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spawn_rewards",
                to="game_parser.gamevertex",
                verbose_name="Узел графа игры. Нужен для связи с локацией",
            ),
        ),
    ]
