# Generated by Django 4.1.3 on 2022-12-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0008_weapon_baseitem_cheat_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseitem",
            name="inv_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название в инвентаре?"
            ),
        ),
        migrations.AlterField(
            model_name="baseitem",
            name="inv_name_short",
            field=models.CharField(
                max_length=255,
                null=True,
                verbose_name="Название в инвентаре(сокращенное)?",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="ammo_class_str",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Боеприпасы"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="ammo_mag_size",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Размер магазина"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="ef_main_weapon_type",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="ef_weapon_type",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="fire_modes_str",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Режимы стрельбы(сырая строка)"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="grenade_class_str",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="Типы гранат для подствольника"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="grenade_launcher_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название ГП"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="grenade_launcher_status",
            field=models.CharField(
                max_length=5, null=True, verbose_name="Возможность установки ГП"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="rpm",
            field=models.IntegerField(
                null=True, verbose_name="Скорострельность выстрелов в минуту"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="scope_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название прицела"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="scope_status_str",
            field=models.CharField(
                max_length=5, null=True, verbose_name="Возможность установки прицела"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="silencer_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Название глушителя"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="silencer_status_str",
            field=models.CharField(
                max_length=5, null=True, verbose_name="Возможность установки глушителя"
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="weapon_class",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
