# Generated by Django 4.1.3 on 2022-12-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0010_addon_explosive_grenade_knife"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrenadeLauncher",
            fields=[
                ("addon_ptr", models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="game_parser.addon")),
                ("ammo_class_str", models.CharField(max_length=255, null=True, verbose_name="Боеприпас")),
            ],
            bases=("game_parser.addon",),
        ),
    ]
