# Generated by Django 4.1.3 on 2022-12-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0011_grenadelauncher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('addon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_parser.addon')),
            ],
            options={
                'verbose_name': 'Прицел',
                'verbose_name_plural': 'Прицелы',
            },
            bases=('game_parser.addon',),
        ),
        migrations.CreateModel(
            name='Silencer',
            fields=[
                ('addon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_parser.addon')),
            ],
            options={
                'verbose_name': 'Глушитель',
                'verbose_name_plural': 'Глушители',
            },
            bases=('game_parser.addon',),
        ),
        migrations.AlterModelOptions(
            name='addon',
            options={'verbose_name': 'Обвес', 'verbose_name_plural': 'Обвесы'},
        ),
        migrations.AlterModelOptions(
            name='ammo',
            options={'verbose_name': 'Боеприпас', 'verbose_name_plural': 'Боеприпасы'},
        ),
        migrations.AlterModelOptions(
            name='cyclicquest',
            options={'verbose_name': 'Циклический квест', 'verbose_name_plural': 'Циклические квесты'},
        ),
        migrations.AlterModelOptions(
            name='explosive',
            options={'verbose_name': 'Взрывчатка', 'verbose_name_plural': 'Взрывчатка'},
        ),
        migrations.AlterModelOptions(
            name='grenade',
            options={'verbose_name': 'Граната', 'verbose_name_plural': 'Гранаты'},
        ),
        migrations.AlterModelOptions(
            name='grenadelauncher',
            options={'verbose_name': 'Подствольный гранатомёт', 'verbose_name_plural': 'Подствольные гранатомёты'},
        ),
        migrations.AlterModelOptions(
            name='knife',
            options={'verbose_name': 'Нож', 'verbose_name_plural': 'Ножи'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Оружие', 'verbose_name_plural': 'Оружие'},
        ),
    ]
