# Generated by Django 4.1.3 on 2022-12-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0012_scope_silencer_alter_addon_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestRandomReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Игровое название"),
                ),
                (
                    "caption",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Человекочитабельное название",
                    ),
                ),
                (
                    "possible_items_str",
                    models.CharField(
                        max_length=2000,
                        verbose_name="Названия возможных предметов",
                    ),
                ),
                (
                    "possible_items",
                    models.ManyToManyField(
                        to="game_parser.baseitem",
                        verbose_name="Возможные предметы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Случайная награда за квест",
                "verbose_name_plural": "Случайные награды за квесты",
            },
        ),
    ]
