# Generated by Django 4.1.3 on 2022-12-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0013_questrandomreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterPart',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_parser.baseitem')),
            ],
            options={
                'verbose_name': 'Часть мутанта',
                'verbose_name_plural': 'Части мутантов',
            },
            bases=('game_parser.baseitem',),
        ),
    ]
