# Generated by Django 4.1.3 on 2022-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0014_monsterpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseitem',
            name='quest_item',
            field=models.BooleanField(default=False, verbose_name='Квестовый предмет'),
        ),
    ]
