# Generated by Django 4.1.3 on 2022-12-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0020_baseitem_inv_grid_height_baseitem_inv_grid_width_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outfit",
            fields=[
                ("baseitem_ptr", models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="game_parser.baseitem")),
                ("burn_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от огня?")),
                ("strike_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от ???")),
                ("shock_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от ???")),
                ("wound_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от ???")),
                ("radiation_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от радиации")),
                ("telepatic_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от телепатии")),
                ("chemical_burn_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от химии")),
                ("explosion_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от взрыва")),
                ("fire_wound_protection", models.DecimalField(decimal_places=4, max_digits=7, verbose_name="Защита от огня?")),
            ],
            options={
                "verbose_name": "Броня",
                "verbose_name_plural": "Броня",
            },
            bases=("game_parser.baseitem",),
        ),
    ]
