# Generated by Django 4.1.3 on 2022-12-12 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0022_artefact"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapsAnom",
            fields=[
                (
                    "artefact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game_parser.artefact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Капсула аномалии",
                "verbose_name_plural": "Капсулы аномалий",
            },
            bases=("game_parser.artefact",),
        ),
        migrations.CreateModel(
            name="MonsterEmbrion",
            fields=[
                (
                    "artefact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game_parser.artefact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эмбрион мутанта",
                "verbose_name_plural": "Эмбрионы мутантов",
            },
            bases=("game_parser.artefact",),
        ),
        migrations.AlterModelOptions(
            name="artefact",
            options={
                "verbose_name": "Базовый артефакт",
                "verbose_name_plural": "Артефакты/Капсулы аномалий/Эмбрионы мутантов",
            },
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="burn_immunity",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="chemical_burn_immunity",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="explosion_immunity",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="fire_wound_immunity",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="health_restore_speed",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="inventory_radiation",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="radiation_immunity",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="shock_immunity",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="strike_immunity",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="telepatic_immunity",
        ),
        migrations.RemoveField(
            model_name="artefact",
            name="wound_immunity",
        ),
        migrations.CreateModel(
            name="TrueArtefact",
            fields=[
                (
                    "artefact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="game_parser.artefact",
                    ),
                ),
                (
                    "inventory_radiation",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Радиоактивность",
                    ),
                ),
                (
                    "health_restore_speed",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Восстановление здоровья?",
                    ),
                ),
                (
                    "burn_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от ???",
                    ),
                ),
                (
                    "strike_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от ???",
                    ),
                ),
                (
                    "shock_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от ???",
                    ),
                ),
                (
                    "wound_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от ???",
                    ),
                ),
                (
                    "radiation_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от радиации",
                    ),
                ),
                (
                    "telepatic_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от телепатии",
                    ),
                ),
                (
                    "chemical_burn_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от химии",
                    ),
                ),
                (
                    "explosion_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от взрыва",
                    ),
                ),
                (
                    "fire_wound_immunity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="Защита от ???",
                    ),
                ),
            ],
            options={
                "verbose_name": "Артефакт",
                "verbose_name_plural": "Артефакты",
            },
            bases=("game_parser.artefact",),
        ),
    ]
