# Generated by Django 4.1.3 on 2022-12-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0023_capsanom_monsterembrion_alter_artefact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trueartefact',
            name='burn_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от ???'),
        ),
        migrations.AlterField(
            model_name='trueartefact',
            name='chemical_burn_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от химии'),
        ),
        migrations.AlterField(
            model_name='trueartefact',
            name='explosion_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от взрыва'),
        ),
        migrations.AlterField(
            model_name='trueartefact',
            name='fire_wound_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от ???'),
        ),
        migrations.AlterField(
            model_name='trueartefact',
            name='radiation_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от радиации'),
        ),
        migrations.AlterField(
            model_name='trueartefact',
            name='shock_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от ???'),
        ),
        migrations.AlterField(
            model_name='trueartefact',
            name='strike_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от ???'),
        ),
        migrations.AlterField(
            model_name='trueartefact',
            name='telepatic_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от телепатии'),
        ),
        migrations.AlterField(
            model_name='trueartefact',
            name='wound_immunity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Защита от ???'),
        ),
    ]
