# Generated by Django 4.1.3 on 2022-12-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0027_basetrade_itemintradebase_trader_buy_sell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminsell',
            name='max_price_modifier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Множитель цены(до)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminsell',
            name='min_price_modifier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Множитель цены(от)'),
            preserve_default=False,
        ),
    ]
