# Generated by Django 4.1.3 on 2022-12-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0031_translation_fra"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseitem",
            name="description_translation",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="game_parser.translation", verbose_name="Перевод описания"),
        ),
        migrations.AddField(
            model_name="baseitem",
            name="name_translation",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="game_parser.translation", verbose_name="Перевод названия"),
        ),
    ]
