# Generated by Django 4.1.3 on 2022-12-27 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0033_baseitem_inv_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclicquest",
            name="target_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game_parser.baseitem",
                verbose_name="Целевой предмет",
            ),
        ),
        migrations.AlterField(
            model_name="baseitem",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название(код в игре)"
            ),
        ),
    ]
