# Generated by Django 4.1.3 on 2022-12-27 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0034_cyclicquest_target_item_alter_baseitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('baseitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game_parser.baseitem')),
            ],
            options={
                'verbose_name': 'Прочий предмет',
                'verbose_name_plural': 'Прочее',
            },
            bases=('game_parser.baseitem',),
        ),
    ]
