# Generated by Django 4.1.3 on 2022-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0035_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitem',
            name='inv_weight',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Вес'),
        ),
    ]
