# Generated by Django 4.1.3 on 2022-12-28 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0036_alter_baseitem_inv_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclicquest',
            name='reward_items',
            field=models.ManyToManyField(related_name='quests_when_giving', to='game_parser.baseitem'),
        ),
        migrations.AlterField(
            model_name='cyclicquest',
            name='target_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests_when_needed', to='game_parser.baseitem', verbose_name='Целевой предмет'),
        ),
    ]
