# Generated by Django 4.1.3 on 2023-01-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0040_alter_location_options_treasure_itemintreasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='custom_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название(2)(код перевода)'),
        ),
        migrations.AddField(
            model_name='treasure',
            name='custom_name_translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game_parser.translation', verbose_name='Перевод названия'),
        ),
    ]
