# Generated by Django 4.1.3 on 2023-01-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0041_treasure_custom_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemintreasure',
            options={'verbose_name': 'Предмет в тайнике', 'verbose_name_plural': 'Предметы в тайниках'},
        ),
        migrations.AlterModelOptions(
            name='treasure',
            options={'verbose_name': 'Тайник', 'verbose_name_plural': 'Тайники'},
        ),
    ]
