# Generated by Django 4.1.3 on 2023-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0046_alter_moneyreward_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemreward",
            name="count",
            field=models.IntegerField(null=True),
        ),
    ]
