# Generated by Django 4.1.3 on 2023-03-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0051_community_gametask_icon_remove_dialog_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskobjective',
            name='icon_raw',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
