# Generated by Django 4.1.3 on 2023-03-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0052_alter_taskobjective_icon_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametask',
            name='game_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='taskobjective',
            name='text_id_raw',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
