# Generated by Django 4.1.3 on 2023-03-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0054_maplocationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskobjective',
            name='function_fail_raw',
            field=models.TextField(null=True),
        ),
    ]
