# Generated by Django 4.1.3 on 2023-03-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0055_taskobjective_function_fail_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplocationtype',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_parser.taskobjective'),
        ),
    ]
