# Generated by Django 4.1.3 on 2023-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0056_alter_maplocationtype_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskobjective',
            name='function_call_complete_raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskobjective',
            name='infoportion_set_fail_raw',
            field=models.TextField(null=True),
        ),
    ]
