# Generated by Django 4.1.3 on 2023-03-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0057_taskobjective_function_call_complete_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialog",
            name="precondition_raw",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="dialogphrase",
            name="precondition_raw",
            field=models.TextField(null=True),
        ),
    ]
