# Generated by Django 4.1.3 on 2023-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0061_dialogphrase_dont_has_info_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialogphrase",
            name="disable_info_raw",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="dialogphrase",
            name="disable_raw",
            field=models.TextField(null=True),
        ),
    ]
