# Generated by Django 4.1.3 on 2023-04-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0063_infoportion"),
    ]

    operations = [
        migrations.AddField(
            model_name="storylinecharacter",
            name="game_id",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storylinecharacter",
            name="name_raw",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storylinecharacter",
            name="name_translation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game_parser.translation",
            ),
        ),
        migrations.AddField(
            model_name="storylinecharacter",
            name="no_random",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="storylinecharacter",
            name="start_dialog_row",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="storylinecharacter",
            name="visual_raw",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="storylinecharacter",
            name="community_default_raw",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
