# Generated by Django 4.1.3 on 2023-04-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0064_storylinecharacter_game_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storylinecharacter",
            name="comments",
            field=models.TextField(null=True),
        ),
    ]
