# Generated by Django 4.1.3 on 2023-04-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0070_alter_icon_icon_alter_icon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskobjective',
            name='article',
        ),
    ]
