# Generated by Django 4.2 on 2023-04-03 20:30

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.contrib.contenttypes.models import ContentType as ContentTypeModel
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def set_reward_content_type(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    ContentType: type[ContentTypeModel] = apps.get_model("contenttypes", "ContentType")
    my_models = [
        "MoneyReward",
        "ItemReward",
        "SpawnReward",
    ]

    for model in my_models:
        MyModel: type[models.Model] = apps.get_model("game_parser", model)
        new_ct = ContentType.objects.get_for_model(MyModel)
        MyModel.objects.filter(polymorphic_ctype__isnull=True).update(
            polymorphic_ctype=new_ct
        )


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("game_parser", "0071_remove_taskobjective_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="basescriptreward",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.RunPython(set_reward_content_type, migrations.RunPython.noop),
    ]
