# Generated by Django 4.2 on 2023-04-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0074_alter_infoportion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyclicquestitemreward',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_rewards', to='game_parser.cyclicquest', verbose_name='Предмет'),
        ),
    ]
