# Generated by Django 4.2 on 2023-04-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0076_alter_cyclicquestitemreward_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameStoryId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story_id", models.PositiveSmallIntegerField(verbose_name="game id")),
                (
                    "section_name",
                    models.CharField(max_length=255, verbose_name="Название секции"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game_parser.baseitem",
                    ),
                ),
                (
                    "treasure",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game_parser.treasure",
                    ),
                ),
            ],
        ),
    ]
