# Generated by Django 4.2 on 2023-05-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0084_remove_cyclicquest_random_rewards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questrandomreward',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.icon', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='questrandomreward',
            name='index',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='questrandomreward',
            name='name_translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.translation', verbose_name='Перевод названия'),
        ),
        migrations.AlterField(
            model_name='questrandomreward',
            name='caption',
            field=models.CharField(max_length=255, null=True, verbose_name='Человекочитабельное название(из комментария)'),
        ),
    ]
