# Generated by Django 4.2 on 2024-01-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0087_spawnitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spawnitem",
            old_name="character_profile",
            new_name="character_profile_str",
        ),
    ]
