# Generated by Django 4.2 on 2024-01-12 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0091_trader2_alter_spawnitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetrade",
            name="trader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game_parser.trader2",
                verbose_name="Торговец",
            ),
        ),
    ]
