# Generated by Django 4.2 on 2024-01-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0092_alter_basetrade_trader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trader',
        ),
    ]
