# Generated by Django 4.2 on 2024-01-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0094_rename_trader2_trader"),
    ]

    operations = [
        migrations.CreateModel(
            name="NpcLogicConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название файла")),
                ("source_file_name", models.CharField(max_length=255, unique=True, verbose_name="Исходный файл")),
                ("trade_file_name", models.CharField(max_length=255, null=True, verbose_name="Название файла торговли")),
            ],
            options={
                "verbose_name": "Логики НПС",
                "verbose_name_plural": "Файлы логик НПС",
            },
        ),
    ]
