# Generated by Django 4.2 on 2024-01-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0101_customspawnitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customspawnitem",
            name="location_txt",
        ),
    ]
