# Generated by Django 4.2 on 2024-01-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0102_remove_customspawnitem_location_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestoryid',
            name='spawn_section_custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.customspawnitem'),
        ),
    ]
