# Generated by Django 4.2 on 2024-01-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0108_alter_locationmapinfo_bound_rect_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spawnitem',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.location'),
        ),
    ]
