# Generated by Django 4.2 on 2024-02-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0113_monster_icon_monster_monster_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="name_translation",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="game_parser.translation"),
        ),
    ]
