# Generated by Django 4.2 on 2024-02-06 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0116_alter_encyclopediaarticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encyclopediaarticle',
            name='artefact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='game_parser.artefact'),
        ),
        migrations.AlterField(
            model_name='encyclopediaarticle',
            name='game_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Игровой id'),
        ),
        migrations.AlterField(
            model_name='encyclopediaarticle',
            name='group_name',
            field=models.CharField(max_length=255, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='encyclopediaarticle',
            name='ltx_str',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Иконка'),
        ),
    ]
