# Generated by Django 4.2 on 2024-02-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0118_recept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recept",
            name="info_raw",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
