# Generated by Django 4.2 on 2024-02-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0120_alter_recept_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=255)),
                ("visual_str", models.CharField(max_length=255)),
                ("hit_type", models.CharField(max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="game_parser.encyclopediaarticle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аномалия",
                "verbose_name_plural": "Аномалии",
            },
        ),
    ]
