# Generated by Django 4.2 on 2024-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0121_anomaly"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anomaly",
            name="hit_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="anomaly",
            name="visual_str",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
