# Generated by Django 4.2 on 2024-02-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0122_alter_anomaly_hit_type_alter_anomaly_visual_str'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseitem',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},
        ),
        migrations.AlterModelOptions(
            name='dialogphrase',
            options={'verbose_name': 'Фраза диалога', 'verbose_name_plural': 'Фразы диалогов'},
        ),
        migrations.AlterModelOptions(
            name='gamestoryid',
            options={'verbose_name': 'Связь id с секциями', 'verbose_name_plural': 'Связи id с секциями'},
        ),
        migrations.AlterModelOptions(
            name='gametask',
            options={'verbose_name': 'Сюжетное задание', 'verbose_name_plural': 'Сюжетные задания'},
        ),
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': 'Иконка', 'verbose_name_plural': 'Иконки'},
        ),
        migrations.AlterModelOptions(
            name='inventorybox',
            options={'verbose_name': 'Тайник', 'verbose_name_plural': 'Тайники'},
        ),
        migrations.AlterModelOptions(
            name='itemintreasurebox',
            options={'verbose_name': 'Предметы в тайнике', 'verbose_name_plural': 'Предметы в тайниках'},
        ),
        migrations.AlterModelOptions(
            name='locationmapinfo',
            options={'verbose_name': 'Дополнительная информация о локации', 'verbose_name_plural': 'Дополнительные данные о локациях'},
        ),
        migrations.AlterModelOptions(
            name='taskobjective',
            options={'verbose_name': 'Цель задания', 'verbose_name_plural': 'Цели заданий'},
        ),
        migrations.AlterField(
            model_name='dialog',
            name='comments_raw',
            field=models.TextField(null=True, verbose_name='комментарии из xml'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='has_info_raw',
            field=models.TextField(null=True, verbose_name='id требуемых инфопоршней'),
        ),
        migrations.AlterField(
            model_name='dialogphrase',
            name='actions_raw',
            field=models.TextField(null=True, verbose_name='Запуск действий(id)'),
        ),
        migrations.AlterField(
            model_name='dialogphrase',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_parser.dialog', verbose_name='Диалог'),
        ),
        migrations.AlterField(
            model_name='dialogphrase',
            name='give_info_raw',
            field=models.TextField(null=True, verbose_name='Получение инфопоршня(id)'),
        ),
        migrations.AlterField(
            model_name='dialogphrase',
            name='local_id',
            field=models.CharField(max_length=10, verbose_name='id фразы в диалоге'),
        ),
        migrations.AlterField(
            model_name='dialogphrase',
            name='next_ids_raw',
            field=models.CharField(max_length=512, verbose_name='id следующих фраз диалога'),
        ),
        migrations.AlterField(
            model_name='dialogphrase',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.dialogphrase', verbose_name='Предыдущая фраза'),
        ),
        migrations.AlterField(
            model_name='dialogphrase',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.translation', verbose_name='Перевод текста'),
        ),
        migrations.AlterField(
            model_name='dialogphrase',
            name='text_id_raw',
            field=models.CharField(max_length=256, null=True, verbose_name='id текста'),
        ),
        migrations.AlterField(
            model_name='gamestoryid',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.storylinecharacter', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='gamestoryid',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.baseitem', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='gamestoryid',
            name='spawn_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.spawnitem', verbose_name='Секция спавна'),
        ),
        migrations.AlterField(
            model_name='gamestoryid',
            name='spawn_section_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.customspawnitem', verbose_name='Кастоная секция спавна'),
        ),
        migrations.AlterField(
            model_name='gamestoryid',
            name='story_id',
            field=models.PositiveSmallIntegerField(verbose_name='id в игре'),
        ),
        migrations.AlterField(
            model_name='gamestoryid',
            name='treasure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.treasure', verbose_name='Тайник'),
        ),
        migrations.AlterField(
            model_name='inventorybox',
            name='section_name',
            field=models.CharField(max_length=255, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='itemintreasurebox',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_parser.inventorybox', verbose_name='Тайник'),
        ),
        migrations.AlterField(
            model_name='itemintreasurebox',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='itemintreasurebox',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_parser.baseitem', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='locationmapinfo',
            name='bound_rect_raw',
            field=models.CharField(max_length=255, null=True, verbose_name='Границы локации(границы картинки?)'),
        ),
        migrations.AlterField(
            model_name='locationmapinfo',
            name='global_rect_raw',
            field=models.CharField(max_length=255, null=True, verbose_name='Границы локации(относительно глобальной карты?)'),
        ),
        migrations.AlterField(
            model_name='locationmapinfo',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_parser.location', verbose_name='локация'),
        ),
        migrations.AlterField(
            model_name='locationmapinfo',
            name='map_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='locationmapinfo',
            name='music_tracks',
            field=models.CharField(max_length=255, null=True, verbose_name='Информация о фоновой музыке'),
        ),
        migrations.AlterField(
            model_name='locationmapinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='locationmapinfo',
            name='texture_raw',
            field=models.CharField(max_length=255, null=True, verbose_name='Название картинки с картой'),
        ),
        migrations.AlterField(
            model_name='locationmapinfo',
            name='weathers',
            field=models.CharField(max_length=255, null=True, verbose_name='Информация о погоде'),
        ),
        migrations.AlterField(
            model_name='spawnreward',
            name='raw_call',
            field=models.TextField(max_length=2048),
        ),
        migrations.AddConstraint(
            model_name='dialogphrase',
            constraint=models.UniqueConstraint(fields=('local_id', 'dialog'), name='unique_dialog_phrase_by_local_id_and_dialog'),
        ),
    ]
