# Generated by Django 4.2 on 2024-04-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0134_alter_campinfo_capacity_alter_campinfo_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campinfo',
            options={'verbose_name': 'Лагерь НПС/мутантов', 'verbose_name_plural': 'Лагеря НПС/мутантов'},
        ),
        migrations.RemoveField(
            model_name='campinfo',
            name='groups',
        ),
        migrations.AddField(
            model_name='campinfo',
            name='groups_str',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='campinfo',
            name='spawn_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_parser.spawnitem', unique=True),
        ),
    ]
