# Generated by Django 4.2 on 2024-04-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0135_alter_campinfo_options_remove_campinfo_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cyclicquest",
            name="target_camp",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="game_parser.campinfo", verbose_name="Цель - лагерь"),
        ),
    ]
