# Generated by Django 4.2.11 on 2024-04-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0140_alter_community_options_remove_community_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="translation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="game_parser.translation",
                verbose_name="Название",
            ),
        ),
    ]
