# Generated by Django 4.2.11 on 2024-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_parser', '0142_alter_community_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='index',
            field=models.PositiveSmallIntegerField(verbose_name='ID группировки'),
        ),
    ]
