# Generated by Django 4.2.11 on 2024-04-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_parser", "0143_alter_community_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encyclopediaarticle",
            name="group_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Группа"),
        ),
    ]
