# Generated by Django 4.2.11 on 2024-04-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalker_op22_cyclic_quest_wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Код иконки для связи с объектами'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stalker_op22_cyclic_quest_wiki.icon', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='location',
            name='map_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stalker_op22_cyclic_quest_wiki.locationmapinfo', verbose_name='Карта локации'),
        ),
        migrations.AlterField(
            model_name='mapposition',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stalker_op22_cyclic_quest_wiki.location', verbose_name='Локация'),
        ),
    ]
