# Generated by Django 4.2.11 on 2024-04-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stalker_op22_cyclic_quest_wiki', '0005_alter_item_description_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletasktargetitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quests_when_needed', to='stalker_op22_cyclic_quest_wiki.item', verbose_name='Целевой предмет'),
        ),
    ]
