# Generated by Django 4.2.11 on 2024-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stalker_op22_cyclic_quest_wiki", "0006_alter_cycletasktargetitem_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapposition",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
    ]
