# Generated by Django 4.2.11 on 2024-05-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stalker_op22_cyclic_quest_wiki",
            "0008_alter_cycletaskvendor_game_story_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemreward",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="moneyreward",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="questrandomreward",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="treasurereward",
            name="polymorphic_ctype",
        ),
        migrations.AlterField(
            model_name="community",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.translation",
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="cycletasktarget",
            name="quest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target",
                to="stalker_op22_cyclic_quest_wiki.cyclicquest",
                unique=True,
                verbose_name="ЦЗ",
            ),
        ),
        migrations.AlterField(
            model_name="cycletasktargetcamp",
            name="communities",
            field=models.ManyToManyField(
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.community",
                verbose_name="Группы в лагере",
            ),
        ),
        migrations.AlterField(
            model_name="cycletasktargetcamp",
            name="map_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="camps_in_position",
                to="stalker_op22_cyclic_quest_wiki.mapposition",
                verbose_name="Место на карте",
            ),
        ),
        migrations.AlterField(
            model_name="cycletasktargetstalker",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.community",
                verbose_name="группа сталкера",
            ),
        ),
        migrations.AlterField(
            model_name="cycletasktargetstalker",
            name="map_positions",
            field=models.ManyToManyField(
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.mapposition",
                verbose_name="Возможные места спавна",
            ),
        ),
        migrations.AlterField(
            model_name="cycletasktargetstalker",
            name="rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.stalkerrank",
                verbose_name="Ранг сталкера",
            ),
        ),
        migrations.AlterField(
            model_name="cycletaskvendor",
            name="icon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.icon",
                verbose_name="Фото НПС",
            ),
        ),
        migrations.AlterField(
            model_name="cycletaskvendor",
            name="name_translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.translation",
                verbose_name="Имя НПС",
            ),
        ),
        migrations.AlterField(
            model_name="cyclicquest",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quests",
                to="stalker_op22_cyclic_quest_wiki.cycletaskvendor",
                verbose_name="Кквестодатель",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="icon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.icon",
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="itemreward",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="use_in_quest_rewards",
                to="stalker_op22_cyclic_quest_wiki.item",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name_translation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.translation",
                verbose_name="Перевод названия",
            ),
        ),
        migrations.AlterField(
            model_name="questrandomreward",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="use_in_quests",
                to="stalker_op22_cyclic_quest_wiki.randomrewardinfo",
                verbose_name="Описание случайной награды",
            ),
        ),
        migrations.AlterField(
            model_name="randomrewardinfo",
            name="description",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.translation",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="randomrewardinfo",
            name="icon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.icon",
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="stalkerrank",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.translation",
                verbose_name="Название",
            ),
        ),
    ]
