# Generated by Django 5.0.4 on 2024-05-22 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stalker_op22_cyclic_quest_wiki",
            "0009_remove_itemreward_polymorphic_ctype_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mapposition",
            unique_together={("x", "y", "z", "location")},
        ),
        migrations.AddField(
            model_name="cycletaskvendor",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="stalker_op22_cyclic_quest_wiki.mapposition",
                verbose_name="Где обитает",
            ),
        ),
        migrations.AddIndex(
            model_name="mapposition",
            index=models.Index(
                fields=["x", "y", "z", "location"],
                name="map_position_index",
            ),
        ),
        migrations.RemoveField(
            model_name="mapposition",
            name="game_vertex_id",
        ),
        migrations.RemoveField(
            model_name="mapposition",
            name="name",
        ),
        migrations.RemoveField(
            model_name="mapposition",
            name="spawn_id",
        ),
        migrations.RemoveField(
            model_name="mapposition",
            name="spawn_story_id",
        ),
        migrations.RemoveField(
            model_name="mapposition",
            name="story_id",
        ),
    ]
