# Generated by Django 5.0.4 on 2024-05-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stalker_op22_cyclic_quest_wiki",
            "0010_alter_mapposition_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mapposition",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Название"),
            preserve_default=False,
        ),
    ]
